---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.2.0
    hooks:
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
        exclude: "^.github/deprecated/.+$"
{%- if cookiecutter.optional_toml_linting == 'true' %}
      - id: format-toml
{%- endif %}
{%- if cookiecutter.optional_workflow_linting == 'true' %}
      - id: lint-github-workflow-header
        exclude: "^.github/deprecated/.+$"
      - id: lint-github-workflow
        exclude: "^.github/deprecated/.+$"
{%- endif %}
      - id: lint-markdown
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: lint-shell
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
        exclude: "^.github/deprecated/.+$"
      - id: security-credentials
      - id: spelling-commit-message
      - id: spelling-markdown
  - repo: local
    hooks:
      - id: check_container
        name: check container
        description: "Check for a valid PIB container."
        entry: ./scripts/hooks/check_container.sh
        language: system
        stages: [commit]
        pass_filenames: false
        require_serial: true
        always_run: true
{%- if cookiecutter.optional_sphinx_support == 'true' %}
      - id: darglint
        name: darglint
        description: 'Check docstrings for Sphinx compliance.'
        entry: darglint
        language: python
        types: [python]
        require_serial: true
{%- endif %}
      - id: protected_branches
        name: protected branches
        description: "Run additional checks on branches marked as protected."
        entry: ./scripts/hooks/protected_branches.sh
        language: system
        stages: [commit]
        pass_filenames: false
        require_serial: true
        always_run: true
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - ".yamllint.yml"
        stages: [commit]
        exclude: "^.github/deprecated/.+$"
