---
version: "3"

services:
  {{cookiecutter.project_slug}}:
    build:
      context: .
      dockerfile: assets/Dockerfile
      target: development
    env_file:
      - assets/local.env
    volumes:
      - ./:/app
