---
version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "{{ cookiecutter.git_base_branch }}"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "{{ cookiecutter.git_username }}"
